### ISSUE TITLE
can't work with any other model file

### ISSUE THREAD

**Issue by roddse3** [guansss/simple-live2d-wallpaper#1]
hi, i am a live2d rigger trying to make my own interactive wallpaper and found this project after trying Neptune Live2D
i was able to follow the whole process with little to no knowledge about coding, and finished building.
but the whole thing would not work if the model file isn't the Ganyu file from sample.
I've tried with verious model files, but thats the only thing working. 
I do not have any experience in coding, so i could not find the reason. 😭

**Comment by guansss** [comment]
Hi, could you explain how it's not working with other models? Is the model not showing, or is there an error message on the page?

**Comment by roddse3** [comment]
Yes I meant model won't show on the wallpaper! No error message, backgrounds do appear, but model won't. I tried many positions if that info help...

**Comment by guansss** [comment]
I see, probably the model is too large and goes outside the window. You can try changing the position and size in `wallpaper/config.json`  and see if it works (requires page reload).

**Comment by roddse3** [comment]
I'm using Tororo model and other Cubism's example model for testing, so i don't think the size is the main problem. I did try different position and size anyway, still doesn't work. I'm sorry i can't provide exact informations 😭

**Comment by roddse3** [comment]
I think i solved it but i don't get how?? thanks for the help!!

**Comment by guansss** [comment]
😂 No problem! I'm glad it's working for you.
